- pkg:apk/alpine/argocd@3.2.0-r0?arch=riscv64&distro=edge
- pkg:apk/alpine/argocd@3.2.0-r1?arch=aarch64&distro=edge
- pkg:apk/alpine/argocd@3.2.0-r1?arch=loongarch64&distro=edge
- pkg:apk/alpine/argocd@3.2.0-r1?arch=ppc64le&distro=edge
